startproject:
	python3 -m django startproject zoo .

runserver:
	python3 manage.py runserver

startapp:
	python3 manage.py startapp <name>

makemigrations:
	python3 manage.py makemigrations

apply migrate:
	python3 manage.py migrate

createsuperuser:
	python3 manage.py createsuperuser

runworker of the Celery:
	celery -A zoo worker -l INFO
