[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
aiohttp = "^3.9.5"
sqlalchemy = {extras = ["asyncio"], version = "^2.0.30"}
asyncpg = "^0.29.0"
alembic = "^1.13.2"
pytest-asyncio = "^0.23.8"
